{% extends 'include/predictor/common/antibiotics.h' %}

{% block additional_functions %}

void print_erythromycin_susceptibility(dBGraph* db_graph,
					  int (*file_reader)(FILE * fp, 
							     Sequence * seq, 
							     int max_read_length, 
							     boolean new_entry, 
							     boolean * full_entry),
					  ReadingUtils* rutils,
					  VarOnBackground* tmp_vob,
					  GeneInfo* tmp_gi,
					  AntibioticInfo* abi,
					  InfectionType (*func)(dBGraph* db_graph,
							 int (*file_reader)(FILE * fp, 
									    Sequence * seq, 
									    int max_read_length, 
									    boolean new_entry, 
									    boolean * full_entry),
							  ReadingUtils* rutils,
							  VarOnBackground* tmp_vob,
							  GeneInfo* tmp_gi,
							  AntibioticInfo* abi,
							  StrBuf* install_dir,
							  int ignore_first, int ignore_last, SpeciesInfo* species_info,
							  double lambda_g, double lambda_e, double err_rate, 
							boolean* any_erm_present,
							  CalledVariant* called_variants,
							  CalledGene* called_genes,
							  CmdLine* cmd_line),
					  StrBuf* tmpbuf,
					  StrBuf* install_dir,
					  int ignore_first, int ignore_last, SpeciesInfo* species_info,
					  double lambda_g, double lambda_e, double err_rate, CmdLine* cmd_line,
					  boolean output_last,
					  boolean* any_erm_present,  InfectionType* erythromycin_resistotype, 
					  CalledVariant* called_variants,CalledGene* called_genes
					  );

void print_clindamycin_susceptibility(dBGraph* db_graph,
					 int (*file_reader)(FILE * fp, 
							    Sequence * seq, 
							    int max_read_length, 
							    boolean new_entry, 
							    boolean * full_entry),
					 ReadingUtils* rutils,
					 VarOnBackground* tmp_vob,
					 GeneInfo* tmp_gi,
					 AntibioticInfo* abi,
					 InfectionType (*func)(dBGraph* db_graph,
							 int (*file_reader)(FILE * fp, 
									    Sequence * seq, 
									    int max_read_length, 
									    boolean new_entry, 
									    boolean * full_entry),
							 ReadingUtils* rutils,
							 VarOnBackground* tmp_vob,
							 GeneInfo* tmp_gi,
							 AntibioticInfo* abi,
							 StrBuf* install_dir,
							 int ignore_first, int ignore_last, SpeciesInfo* species_info,
							 double lambda_g, double lambda_e, double err_rate,
							 CalledVariant* called_variants,CalledGene* called_genes,
							 CmdLine* cmd_line),
					 StrBuf* tmpbuf,
					 boolean any_erm_present, InfectionType erythromycin_resistotype, 
					 StrBuf* install_dir,
					 int ignore_first, int ignore_last, SpeciesInfo* species_info,
					 double lambda_g, double lambda_e, double err_rate, CmdLine* cmd_line,
					 boolean output_last,
					 CalledVariant* called_variants,CalledGene* called_genes
					 );
{% endblock %}
