/*
 * Copyright 2014 Zamin Iqbal (zam@well.ox.ac.uk)
 * 
 *
 *  species.h
*/

/*
 * Copyright 2014 Zamin Iqbal (zam@well.ox.ac.uk)
 * 
 *
 *  base_species.h
*/
#include "dB_graph.h"

#ifdef STAPH

typedef enum 
 {
   CoagPos = 0,
   CoagNeg = 1
} PhyloGroup ;

#define NUM_COMPLEX 2

//  typedef enum 
// {
// Saureus=0,
// Sepidermidis = 1,
// Shaemolyticus = 2,
// Sother=3
// } Species ;

typedef enum name
{
  Achromobacter_piechaudii = 0,
  Achromobacter_xylosoxidans = 1,
  Acidaminococcus_fermentans = 2,
  Acidithiobacillus_caldus = 3,
  Acidithiobacillus_ferrooxidans = 4,
  Acidovorax_avenae = 5,
  Acidovorax_delafieldii = 6,
  Acinetobacter_baumannii = 7,
  Acinetobacter_calcoaceticus = 8,
  Acinetobacter_haemolyticus = 9,
  Acinetobacter_johnsonii = 10,
  Acinetobacter_junii = 11,
  Acinetobacter_lwoffii = 12,
  Acinetobacter_radioresistens = 13,
  Actinobacillus_minor = 14,
  Actinobacillus_pleuropneumoniae = 15,
  Actinobacillus_succinogenes = 16,
  Actinobacillus_ureae = 17,
  Actinomyces_coleocanis = 18,
  Actinomyces_odontolyticus = 19,
  Actinomyces_oris = 20,
  Actinomyces_urogenitalis = 21,
  Actinomyces_viscosus = 22,
  Aeromonas_hydrophila = 23,
  Aeromonas_salmonicida = 24,
  Aggregatibacter_actinomycetemcomitans = 25,
  Aggregatibacter_aphrophilus = 26,
  Aggregatibacter_segnis = 27,
  Agrobacterium_tumefaciens = 28,
  Agrobacterium_vitis = 29,
  Alcanivorax_borkumensis = 30,
  Alicyclobacillus_acidocaldarius = 31,
  Alicyclobacillus_Alicyclobacillus = 32,
  Aliivibrio_fischeri = 33,
  Aliivibrio_salmonicida = 34,
  Alistipes_putredinis = 35,
  Alistipes_shahii = 36,
  Alkaliphilus_metalliredigens = 37,
  Alkaliphilus_oremlandii = 38,
  Anabaena_azollae = 39,
  Anabaena_variabilis = 40,
  Anaerococcus_hydrogenalis = 41,
  Anaerococcus_lactolyticus = 42,
  Anaerococcus_prevotii = 43,
  Anaerococcus_tetradius = 44,
  Anaerococcus_vaginalis = 45,
  Anaeromyxobacter_dehalogenans = 46,
  Anaerostipes_caccae = 47,
  Anaplasma_centrale = 48,
  Anaplasma_marginale = 49,
  Anaplasma_phagocytophilum = 50,
  Archaeoglobus_fulgidus = 51,
  Archaeoglobus_profundus = 52,
  Arcobacter_butzleri = 53,
  Arcobacter_nitrofigilis = 54,
  Arthrobacter_arilaitensis = 55,
  Arthrobacter_aurescens = 56,
  Arthrobacter_chlorophenolicus = 57,
  Arthrobacter_phenanthrenivorans = 58,
  Arthrospira_maxima = 59,
  Arthrospira_platensis = 60,
  Atopobium_parvulum = 61,
  Atopobium_rimae = 62,
  Atopobium_vaginae = 63,
  Bacillus_amyloliquefaciens = 64,
  Bacillus_anthracis = 65,
  Bacillus_atrophaeus = 66,
  Bacillus_cellulosilyticus = 67,
  Bacillus_cereus = 68,
  Bacillus_clausii = 69,
  Bacillus_coagulans = 70,
  Bacillus_coahuilensis = 71,
  Bacillus_halodurans = 72,
  Bacillus_licheniformis = 73,
  Bacillus_megaterium = 74,
  Bacillus_mycoides = 75,
  Bacillus_pseudofirmus = 76,
  Bacillus_pseudomycoides = 77,
  Bacillus_pumilus = 78,
  Bacillus_selenitireducens = 79,
  Bacillus_subtilis = 80,
  Bacillus_thuringiensis = 81,
  Bacillus_weihenstephanensis = 82,
  Bacteroides_caccae = 83,
  Bacteroides_cellulosilyticus = 84,
  Bacteroides_coprocola = 85,
  Bacteroides_coprophilus = 86,
  Bacteroides_dorei = 87,
  Bacteroides_eggerthii = 88,
  Bacteroides_finegoldii = 89,
  Bacteroides_fragilis = 90,
  Bacteroides_helcogenes = 91,
  Bacteroides_intestinalis = 92,
  Bacteroides_ovatus = 93,
  Bacteroides_pectinophilus = 94,
  Bacteroides_plebeius = 95,
  Bacteroides_salanitronis = 96,
  Bacteroides_stercoris = 97,
  Bacteroides_thetaiotaomicron = 98,
  Bacteroides_uniformis = 99,
  Bacteroides_vulgatus = 100,
  Bacteroides_xylanisolvens = 101,
  Bartonella_bacilliformis = 102,
  Bartonella_clarridgeiae = 103,
  Bartonella_grahamii = 104,
  Bartonella_henselae = 105,
  Bartonella_quintana = 106,
  Bartonella_tribocorum = 107,
  Bifidobacterium_adolescentis = 108,
  Bifidobacterium_angulatum = 109,
  Bifidobacterium_animalis = 110,
  Bifidobacterium_bifidum = 111,
  Bifidobacterium_breve = 112,
  Bifidobacterium_catenulatum = 113,
  Bifidobacterium_dentium = 114,
  Bifidobacterium_gallicum = 115,
  Bifidobacterium_longum = 116,
  Bifidobacterium_pseudocatenulatum = 117,
  Blautia_hansenii = 118,
  Blautia_hydrogenotrophica = 119,
  Bordetella_avium = 120,
  Bordetella_bronchiseptica = 121,
  Bordetella_parapertussis = 122,
  Bordetella_pertussis = 123,
  Bordetella_petrii = 124,
  Borrelia_afzelii = 125,
  Borrelia_burgdorferi = 126,
  Borrelia_duttonii = 127,
  Borrelia_garinii = 128,
  Borrelia_hermsii = 129,
  Borrelia_recurrentis = 130,
  Borrelia_spielmanii = 131,
  Borrelia_turicatae = 132,
  Borrelia_valaisiana = 133,
  Brachyspira_hyodysenteriae = 134,
  Brachyspira_murdochii = 135,
  Brachyspira_pilosicoli = 136,
  Bradyrhizobium_japonicum = 137,
  Brevibacterium_linens = 138,
  Brevibacterium_mcbrellneri = 139,
  Brevundimonas_subvibrioides = 140,
  Brucella_abortus = 141,
  Brucella_canis = 142,
  Brucella_ceti = 143,
  Brucella_melitensis = 144,
  Brucella_microti = 145,
  Brucella_neotomae = 146,
  Brucella_ovis = 147,
  Brucella_pinnipedialis = 148,
  Brucella_suis = 149,
  Burkholderia_ambifaria = 150,
  Burkholderia_cenocepacia = 151,
  Burkholderia_cepacia = 152,
  Burkholderia_dolosa = 153,
  Burkholderia_glumae = 154,
  Burkholderia_graminis = 155,
  Burkholderia_mallei = 156,
  Burkholderia_multivorans = 157,
  Burkholderia_oklahomensis = 158,
  Burkholderia_phymatum = 159,
  Burkholderia_phytofirmans = 160,
  Burkholderia_pseudomallei = 161,
  Burkholderia_rhizoxinica = 162,
  Burkholderia_thailandensis = 163,
  Burkholderia_ubonensis = 164,
  Burkholderia_vietnamiensis = 165,
  Burkholderia_xenovorans = 166,
  Butyrivibrio_crossotus = 167,
  Butyrivibrio_fibrisolvens = 168,
  Butyrivibrio_proteoclasticus = 169,
  Caldanaerobacter_pacificum = 170,
  Caldanaerobacter_tengcongensis = 171,
  Caldicellulosiruptor_bescii = 172,
  Caldicellulosiruptor_hydrothermalis = 173,
  Caldicellulosiruptor_kristjanssonii = 174,
  Caldicellulosiruptor_kronotskyensis = 175,
  Caldicellulosiruptor_lactoaceticus = 176,
  Caldicellulosiruptor_obsidiansis = 177,
  Caldicellulosiruptor_owensensis = 178,
  Caldicellulosiruptor_saccharolyticus = 179,
  Campylobacter_coli = 180,
  Campylobacter_concisus = 181,
  Campylobacter_curvus = 182,
  Campylobacter_fetus = 183,
  Campylobacter_gracilis = 184,
  Campylobacter_hominis = 185,
  Campylobacter_jejuni = 186,
  Campylobacter_lari = 187,
  Campylobacter_rectus = 188,
  Campylobacter_showae = 189,
  Campylobacter_upsaliensis = 190,
  Candidatus_Blochmannia_floridanus = 191,
  Candidatus_Blochmannia_pennsylvanicus = 192,
  Candidatus_Pelagibacter_ubique = 193,
  Candidatus_Phytoplasma_yellows = 194,
  Candidatus_Sulcia_muelleri = 195,
  Capnocytophaga_gingivalis = 196,
  Capnocytophaga_ochracea = 197,
  Capnocytophaga_sputigena = 198,
  Caulobacter_crescentus = 199,
  Caulobacter_segnis = 200,
  Cellulophaga_algicola = 201,
  Cellulophaga_lytica = 202,
  Chlamydia_muridarum = 203,
  Chlamydia_trachomatis = 204,
  Chlamydophila_abortus = 205,
  Chlamydophila_caviae = 206,
  Chlamydophila_felis = 207,
  Chlamydophila_pneumoniae = 208,
  Chlamydophila_psittaci = 209,
  Chlorobaculum_parvum = 210,
  Chlorobaculum_tepidum = 211,
  Chlorobium_chlorochromatii = 212,
  Chlorobium_ferrooxidans = 213,
  Chlorobium_limicola = 214,
  Chlorobium_phaeobacteroides = 215,
  Chlorobium_vibrioformis = 216,
  Chloroflexus_aggregans = 217,
  Chloroflexus_aurantiacus = 218,
  Citrobacter_koseri = 219,
  Citrobacter_rodentium = 220,
  Citrobacter_youngae = 221,
  Clostridium_acetobutylicum = 222,
  Clostridium_asparagiforme = 223,
  Clostridium_bartlettii = 224,
  Clostridium_beijerinckii = 225,
  Clostridium_bolteae = 226,
  Clostridium_botulinum = 227,
  Clostridium_butyricum = 228,
  Clostridium_carboxidivorans = 229,
  Clostridium_cellulolyticum = 230,
  Clostridium_cellulovorans = 231,
  Clostridium_cf = 232,
  Clostridium_difficile = 233,
  Clostridium_hathewayi = 234,
  Clostridium_hiranonis = 235,
  Clostridium_hylemonae = 236,
  Clostridium_kluyveri = 237,
  Clostridium_leptum = 238,
  Clostridium_ljungdahlii = 239,
  Clostridium_methylpentosum = 240,
  Clostridium_nexile = 241,
  Clostridium_novyi = 242,
  Clostridium_papyrosolvens = 243,
  Clostridium_perfringens = 244,
  Clostridium_phytofermentans = 245,
  Clostridium_saccharolyticum = 246,
  Clostridium_scindens = 247,
  Clostridium_sporogenes = 248,
  Clostridium_sticklandii = 249,
  Clostridium_symbiosum = 250,
  Clostridium_tetani = 251,
  Clostridium_thermocellum = 252,
  Collinsella_aerofaciens = 253,
  Collinsella_intestinalis = 254,
  Collinsella_stercoris = 255,
  Coprobacillus_bacterium = 256,
  Coprococcus_catus = 257,
  Coprococcus_comes = 258,
  Coprococcus_eutactus = 259,
  Corynebacterium_accolens = 260,
  Corynebacterium_ammoniagenes = 261,
  Corynebacterium_amycolatum = 262,
  Corynebacterium_aurimucosum = 263,
  Corynebacterium_diphtheriae = 264,
  Corynebacterium_efficiens = 265,
  Corynebacterium_genitalium = 266,
  Corynebacterium_glucuronolyticum = 267,
  Corynebacterium_glutamicum = 268,
  Corynebacterium_jeikeium = 269,
  Corynebacterium_kroppenstedtii = 270,
  Corynebacterium_lipophiloflavum = 271,
  Corynebacterium_matruchotii = 272,
  Corynebacterium_pseudogenitalium = 273,
  Corynebacterium_pseudotuberculosis = 274,
  Corynebacterium_resistens = 275,
  Corynebacterium_striatum = 276,
  Corynebacterium_tuberculostearicum = 277,
  Corynebacterium_urealyticum = 278,
  Corynebacterium_variabile = 279,
  Cronobacter_sakazakii = 280,
  Cronobacter_turicensis = 281,
  Cupriavidus_eutropha = 282,
  Cupriavidus_metallidurans = 283,
  Cupriavidus_taiwanensis = 284,
  Dehalococcoides_ethenogenes = 285,
  Deinococcus_deserti = 286,
  Deinococcus_geothermalis = 287,
  Deinococcus_maricopensis = 288,
  Deinococcus_proteolyticus = 289,
  Deinococcus_radiodurans = 290,
  Desulfotomaculum_acetoxidans = 291,
  Desulfotomaculum_nigrificans = 292,
  Desulfotomaculum_reducens = 293,
  Desulfovibrio_aespoeensis = 294,
  Desulfovibrio_desulfuricans = 295,
  Desulfovibrio_fructosovorans = 296,
  Desulfovibrio_magneticus = 297,
  Desulfovibrio_piger = 298,
  Desulfovibrio_salexigens = 299,
  Desulfovibrio_vulgaris = 300,
  Desulfurococcus_kamchatkensis = 301,
  Desulfurococcus_mucosus = 302,
  Dialister_invisus = 303,
  Dialister_microaerophilus = 304,
  Dickeya_dadantii = 305,
  Dickeya_zeae = 306,
  Dictyoglomus_thermophilum = 307,
  Dictyoglomus_turgidum = 308,
  Dorea_formicigenerans = 309,
  Dorea_longicatena = 310,
  Edwardsiella_ictaluri = 311,
  Edwardsiella_tarda = 312,
  Eggerthella_lenta = 313,
  Ehrlichia_canis = 314,
  Ehrlichia_chaffeensis = 315,
  Ehrlichia_ruminantium = 316,
  Ensifer_medicae = 317,
  Ensifer_meliloti = 318,
  Enterobacter_cancerogenus = 319,
  Enterobacter_cloacae = 320,
  Enterococcus_casseliflavus = 321,
  Enterococcus_faecalis = 322,
  Enterococcus_faecium = 323,
  Enterococcus_gallinarum = 324,
  Enterococcus_italicus = 325,
  Erwinia_amylovora = 326,
  Erwinia_billingiae = 327,
  Erwinia_pyrifoliae = 328,
  Erwinia_tasmaniensis = 329,
  Erythrobacter_litoralis = 330,
  Escherichia_albertii = 331,
  Escherichia_coli = 332,
  Escherichia_fergusonii = 333,
  Eubacterium_cellulosolvens = 334,
  Eubacterium_eligens = 335,
  Eubacterium_hallii = 336,
  Eubacterium_limosum = 337,
  Eubacterium_rectale = 338,
  Eubacterium_saburreum = 339,
  Eubacterium_saphenum = 340,
  Eubacterium_siraeum = 341,
  Eubacterium_ventriosum = 342,
  Exiguobacterium_sibiricum = 343,
  Faecalibacterium_cf = 344,
  Faecalibacterium_prausnitzii = 345,
  Flavobacterium_johnsoniae = 346,
  Flavobacterium_psychrophilum = 347,
  Francisella_novicida = 348,
  Francisella_philomiragia = 349,
  Francisella_tularensis = 350,
  Frankia_alni = 351,
  Frankia_symbiont = 352,
  Fusobacterium_gonidiaformans = 353,
  Fusobacterium_mortiferum = 354,
  Fusobacterium_nucleatum = 355,
  Fusobacterium_periodonticum = 356,
  Fusobacterium_ulcerans = 357,
  Fusobacterium_varium = 358,
  Gemella_haemolysans = 359,
  Gemella_moribillum = 360,
  Geobacillus_kaustophilus = 361,
  Geobacillus_thermodenitrificans = 362,
  Geobacillus_thermoglucosidasius = 363,
  Geobacter_bemidjiensis = 364,
  Geobacter_lovleyi = 365,
  Geobacter_metallireducens = 366,
  Geobacter_sulfurreducens = 367,
  Geobacter_uraniumreducens = 368,
  Gluconacetobacter_diazotrophicus = 369,
  Gluconacetobacter_hansenii = 370,
  Granulicatella_adiacens = 371,
  Granulicatella_elegans = 372,
  Haemophilus_ducreyi = 373,
  Haemophilus_influenzae = 374,
  Haemophilus_parainfluenzae = 375,
  Haemophilus_parasuis = 376,
  Halanaerobium_praevalens = 377,
  Halobacterium_salinarum = 378,
  Helicobacter_acinonychis = 379,
  Helicobacter_bilis = 380,
  Helicobacter_canadensis = 381,
  Helicobacter_cinaedi = 382,
  Helicobacter_felis = 383,
  Helicobacter_hepaticus = 384,
  Helicobacter_mustelae = 385,
  Helicobacter_pullorum = 386,
  Helicobacter_pylori = 387,
  Helicobacter_suis = 388,
  Helicobacter_winghamensis = 389,
  Idiomarina_baltica = 390,
  Idiomarina_loihiensis = 391,
  Kingella_denitrificans = 392,
  Kingella_oralis = 393,
  Klebsiella_pneumoniae = 394,
  Klebsiella_variicola = 395,
  Labrenzia_aggregata = 396,
  Labrenzia_alexandrii = 397,
  Lactobacillus_acidophilus = 398,
  Lactobacillus_amylolyticus = 399,
  Lactobacillus_amylovorus = 400,
  Lactobacillus_antri = 401,
  Lactobacillus_brevis = 402,
  Lactobacillus_buchneri = 403,
  Lactobacillus_casei = 404,
  Lactobacillus_coleohominis = 405,
  Lactobacillus_crispatus = 406,
  Lactobacillus_delbrueckii = 407,
  Lactobacillus_fermentum = 408,
  Lactobacillus_gasseri = 409,
  Lactobacillus_helveticus = 410,
  Lactobacillus_hilgardii = 411,
  Lactobacillus_iners = 412,
  Lactobacillus_jensenii = 413,
  Lactobacillus_johnsonii = 414,
  Lactobacillus_oris = 415,
  Lactobacillus_paracasei = 416,
  Lactobacillus_plantarum = 417,
  Lactobacillus_reuteri = 418,
  Lactobacillus_rhamnosus = 419,
  Lactobacillus_ruminis = 420,
  Lactobacillus_sakei = 421,
  Lactobacillus_salivarius = 422,
  Lactobacillus_ultunensis = 423,
  Lactobacillus_vaginalis = 424,
  Legionella_drancourtii = 425,
  Legionella_longbeachae = 426,
  Legionella_pneumophila = 427,
  Leptospira_biflexa = 428,
  Leptospira_borgpetersenii = 429,
  Leptospira_interrogans = 430,
  Leptotrichia_buccalis = 431,
  Leptotrichia_goodfellowii = 432,
  Leptotrichia_hofstadii = 433,
  Leuconostoc_citreum = 434,
  Leuconostoc_gasicomitatum = 435,
  Leuconostoc_kimchii = 436,
  Leuconostoc_mesenteroides = 437,
  Listeria_grayi = 438,
  Listeria_innocua = 439,
  Listeria_monocytogenes = 440,
  Listeria_seeligeri = 441,
  Listeria_welshimeri = 442,
  Loktanella_vestfoldensis = 443,
  Lysinibacillus_fusiformis = 444,
  Lysinibacillus_sphaericus = 445,
  Magnetospirillum_magneticum = 446,
  Magnetospirillum_magnetotacticum = 447,
  Marinobacter_algicola = 448,
  Marinobacter_aquaeolei = 449,
  Marinobacter_bacterium = 450,
  Megasphaera_micronuciformis = 451,
  Meiothermus_ruber = 452,
  Meiothermus_silvanus = 453,
  Mesorhizobium_ciceri = 454,
  Mesorhizobium_loti = 455,
  Mesorhizobium_opportunistum = 456,
  Methanobrevibacter_ruminantium = 457,
  Methanobrevibacter_smithii = 458,
  Methanocaldococcus_fervens = 459,
  Methanocaldococcus_infernus = 460,
  Methanocaldococcus_jannaschii = 461,
  Methanocaldococcus_vulcanius = 462,
  Methanocella_paludicola = 463,
  Methanococcus_aeolicus = 464,
  Methanococcus_maripaludis = 465,
  Methanococcus_vannielii = 466,
  Methanococcus_voltae = 467,
  Methanosarcina_acetivorans = 468,
  Methanosarcina_barkeri = 469,
  Methanosarcina_mazei = 470,
  Methanothermobacter_marburgensis = 471,
  Methanothermobacter_thermautotrophicus = 472,
  Methylobacterium_chloromethanicum = 473,
  Methylobacterium_extorquens = 474,
  Methylobacterium_nodulans = 475,
  Methylobacterium_populi = 476,
  Methylobacterium_radiotolerans = 477,
  Methylotenera_mobilis = 478,
  Micromonospora_aurantiaca = 479,
  Mobiluncus_curtisii = 480,
  Mobiluncus_mulieris = 481,
  Mycobacterium_abscessus = 482,
  Mycobacterium_avium = 483,
  Mycobacterium_bovis = 484,
  Mycobacterium_gilvum = 485,
  Mycobacterium_intracellulare = 486,
  Mycobacterium_kansasii = 487,
  Mycobacterium_leprae = 488,
  Mycobacterium_marinum = 489,
  Mycobacterium_parascrofulaceum = 490,
  Mycobacterium_smegmatis = 491,
  Mycobacterium_tuberculosis = 492,
  Mycobacterium_ulcerans = 493,
  Mycobacterium_vanbaalenii = 494,
  Mycoplasma_agalactiae = 495,
  Mycoplasma_alligatoris = 496,
  Mycoplasma_arthritidis = 497,
  Mycoplasma_bovis = 498,
  Mycoplasma_capricolum = 499,
  Mycoplasma_conjunctivae = 500,
  Mycoplasma_crocodyli = 501,
  Mycoplasma_fermentans = 502,
  Mycoplasma_gallisepticum = 503,
  Mycoplasma_genitalium = 504,
  Mycoplasma_haemofelis = 505,
  Mycoplasma_hominis = 506,
  Mycoplasma_hyopneumoniae = 507,
  Mycoplasma_hyorhinis = 508,
  Mycoplasma_leachii = 509,
  Mycoplasma_mobile = 510,
  Mycoplasma_mycoides = 511,
  Mycoplasma_penetrans = 512,
  Mycoplasma_pneumoniae = 513,
  Mycoplasma_pulmonis = 514,
  Mycoplasma_synoviae = 515,
  Neisseria_cinerea = 516,
  Neisseria_elongata = 517,
  Neisseria_flavescens = 518,
  Neisseria_gonorrhoeae = 519,
  Neisseria_lactamica = 520,
  Neisseria_meningitidis = 521,
  Neisseria_mucosa = 522,
  Neisseria_polysaccharea = 523,
  Neisseria_sicca = 524,
  Neisseria_subflava = 525,
  Neorickettsia_risticii = 526,
  Neorickettsia_sennetsu = 527,
  Nitrobacter_hamburgensis = 528,
  Nitrobacter_winogradskyi = 529,
  Nitrosococcus_halophilus = 530,
  Nitrosococcus_oceani = 531,
  Nitrosococcus_watsoni = 532,
  Nitrosomonas_europaea = 533,
  Nitrosomonas_eutropha = 534,
  Nostoc_punctiforme = 535,
  Oceanicola_batsensis = 536,
  Oceanicola_granulosus = 537,
  Ochrobactrum_anthropi = 538,
  Ochrobactrum_intermedium = 539,
  Oribacterium_sinus = 540,
  Paenibacillus_curdlanolyticus = 541,
  Paenibacillus_larvae = 542,
  Paenibacillus_polymyxa = 543,
  Paenibacillus_vortex = 544,
  Pantoea_ananatis = 545,
  Pantoea_vagans = 546,
  Parabacteroides_distasonis = 547,
  Parabacteroides_johnsonii = 548,
  Parabacteroides_merdae = 549,
  Pasteurella_dagmatis = 550,
  Pasteurella_multocida = 551,
  Pectobacterium_carotovora = 552,
  Pectobacterium_carotovorum = 553,
  Pectobacterium_wasabiae = 554,
  Pediococcus_acidilactici = 555,
  Pediococcus_pentosaceus = 556,
  Pedobacter_heparinus = 557,
  Pedobacter_saltans = 558,
  Pelobacter_carbinolicus = 559,
  Pelobacter_propionicus = 560,
  Pelodictyon_clathratiforme = 561,
  Pelodictyon_luteolum = 562,
  Peptoniphilus_duerdenii = 563,
  Peptoniphilus_harei = 564,
  Peptoniphilus_lacrimalis = 565,
  Peptostreptococcus_anaerobius = 566,
  Peptostreptococcus_stomatis = 567,
  Photobacterium_angustum = 568,
  Photobacterium_damselae = 569,
  Photobacterium_profundum = 570,
  Photorhabdus_asymbiotica = 571,
  Photorhabdus_luminescens = 572,
  Planctomyces_brasiliensis = 573,
  Planctomyces_limnophilus = 574,
  Planctomyces_maris = 575,
  Polaribacter_irgensii = 576,
  Polaromonas_naphthalenivorans = 577,
  Polynucleobacter_necessarius = 578,
  Porphyromonas_asaccharolytica = 579,
  Porphyromonas_endodontalis = 580,
  Porphyromonas_gingivalis = 581,
  Porphyromonas_uenonis = 582,
  Prevotella_amnii = 583,
  Prevotella_bergensis = 584,
  Prevotella_bivia = 585,
  Prevotella_bryantii = 586,
  Prevotella_buccae = 587,
  Prevotella_buccalis = 588,
  Prevotella_copri = 589,
  Prevotella_disiens = 590,
  Prevotella_marshii = 591,
  Prevotella_melaninogenica = 592,
  Prevotella_multiformis = 593,
  Prevotella_oralis = 594,
  Prevotella_oris = 595,
  Prevotella_ruminicola = 596,
  Prevotella_salivae = 597,
  Prevotella_tannerae = 598,
  Prevotella_timonensis = 599,
  Prevotella_veroralis = 600,
  Propionibacterium_acnes = 601,
  Propionibacterium_freudenreichii = 602,
  Proteus_mirabilis = 603,
  Proteus_penneri = 604,
  Providencia_alcalifaciens = 605,
  Providencia_rettgeri = 606,
  Providencia_rustigianii = 607,
  Providencia_stuartii = 608,
  Pseudoalteromonas_atlantica = 609,
  Pseudoalteromonas_haloplanktis = 610,
  Pseudoalteromonas_tunicata = 611,
  Pseudomonas_aeruginosa = 612,
  Pseudomonas_entomophila = 613,
  Pseudomonas_fluorescens = 614,
  Pseudomonas_mendocina = 615,
  Pseudomonas_putida = 616,
  Pseudomonas_savastanoi = 617,
  Pseudomonas_stutzeri = 618,
  Pseudomonas_syringae = 619,
  Psychrobacter_arcticus = 620,
  Psychrobacter_cryohalolentis = 621,
  Psychromonas_ingrahamii = 622,
  Pyrobaculum_aerophilum = 623,
  Pyrobaculum_arsenaticum = 624,
  Pyrobaculum_calidifontis = 625,
  Pyrobaculum_islandicum = 626,
  Pyrococcus_abyssi = 627,
  Pyrococcus_furiosus = 628,
  Pyrococcus_horikoshii = 629,
  Ralstonia_pickettii = 630,
  Ralstonia_solanacearum = 631,
  Rhizobium_etli = 632,
  Rhizobium_leguminosarum = 633,
  Rhizobium_radiobacter = 634,
  Rhodobacter_capsulatus = 635,
  Rhodobacter_sphaeroides = 636,
  Rhodococcus_equi = 637,
  Rhodococcus_erythropolis = 638,
  Rhodococcus_opacus = 639,
  Rickettsia_africae = 640,
  Rickettsia_akari = 641,
  Rickettsia_bellii = 642,
  Rickettsia_canadensis = 643,
  Rickettsia_conorii = 644,
  Rickettsia_endosymbiont = 645,
  Rickettsia_felis = 646,
  Rickettsia_massiliae = 647,
  Rickettsia_peacockii = 648,
  Rickettsia_prowazekii = 649,
  Rickettsia_rickettsii = 650,
  Rickettsia_sibirica = 651,
  Rickettsia_typhi = 652,
  Roseburia_intestinalis = 653,
  Roseburia_inulinivorans = 654,
  Roseiflexus_castenholzii = 655,
  Roseobacter_denitrificans = 656,
  Roseobacter_litoralis = 657,
  Roseovarius_nubinhibens = 658,
  Rothia_dentocariosa = 659,
  Rothia_mucilaginosa = 660,
  Ruegeria_lacuscaerulensis = 661,
  Ruegeria_pomeroyi = 662,
  Ruminococcus_albus = 663,
  Ruminococcus_bromii = 664,
  Ruminococcus_flavefaciens = 665,
  Ruminococcus_gnavus = 666,
  Ruminococcus_lactaris = 667,
  Ruminococcus_obeum = 668,
  Ruminococcus_torques = 669,
  Salinispora_arenicola = 670,
  Salinispora_tropica = 671,
  Salmonella_enterica = 672,
  Salmonella_typhimurium = 673,
  Segniliparus_rotundus = 674,
  Segniliparus_rugosus = 675,
  Selenomonas_artemidis = 676,
  Selenomonas_flueggei = 677,
  Selenomonas_noxia = 678,
  Selenomonas_sputigena = 679,
  Serratia_odorifera = 680,
  Serratia_proteamaculans = 681,
  Shewanella_amazonensis = 682,
  Shewanella_baltica = 683,
  Shewanella_benthica = 684,
  Shewanella_denitrificans = 685,
  Shewanella_frigidimarina = 686,
  Shewanella_halifaxensis = 687,
  Shewanella_loihica = 688,
  Shewanella_oneidensis = 689,
  Shewanella_pealeana = 690,
  Shewanella_piezotolerans = 691,
  Shewanella_putrefaciens = 692,
  Shewanella_sediminis = 693,
  Shewanella_violacea = 694,
  Shewanella_woodyi = 695,
  Shigella_boydii = 696,
  Shigella_dysenteriae = 697,
  Shigella_flexneri = 698,
  Shigella_sonnei = 699,
  Slackia_exigua = 700,
  Slackia_heliotrinireducens = 701,
  Sphingobium_chlorophenolicum = 702,
  Sphingobium_japonicum = 703,
  Sphingomonas_wittichii = 704,
  Spirochaeta_smaragdinae = 705,
  Spirochaeta_thermophila = 706,
  Saureus = 707,
  Scapitis = 708,
  Scarnosus = 709,
  Sepidermidis = 710,
  Shaemolyticus = 711,
  Shominis = 712,
  Slugdunensis = 713,
  Spseudintermedius = 714,
  Ssaprophyticus = 715,
  Swarneri = 716,
  Staphylothermus_hellenicus = 717,
  Staphylothermus_marinus = 718,
  Stenotrophomonas_maltophilia = 719,
  Streptococcus_agalactiae = 720,
  Streptococcus_anginosus = 721,
  Streptococcus_australis = 722,
  Streptococcus_bovis = 723,
  Streptococcus_cristatus = 724,
  Streptococcus_downei = 725,
  Streptococcus_dysgalactiae = 726,
  Streptococcus_equi = 727,
  Streptococcus_equinus = 728,
  Streptococcus_gallolyticus = 729,
  Streptococcus_gordonii = 730,
  Streptococcus_infantarius = 731,
  Streptococcus_infantis = 732,
  Streptococcus_mitis = 733,
  Streptococcus_mutans = 734,
  Streptococcus_oralis = 735,
  Streptococcus_parasanguinis = 736,
  Streptococcus_peroris = 737,
  Streptococcus_pneumoniae = 738,
  Streptococcus_pseudoporcinus = 739,
  Streptococcus_pyogenes = 740,
  Streptococcus_salivarius = 741,
  Streptococcus_sanguinis = 742,
  Streptococcus_suis = 743,
  Streptococcus_thermophilus = 744,
  Streptococcus_uberis = 745,
  Streptococcus_vestibularis = 746,
  Streptomyces_albus = 747,
  Streptomyces_avermitilis = 748,
  Streptomyces_bingchenggensis = 749,
  Streptomyces_clavuligerus = 750,
  Streptomyces_coelicolor = 751,
  Streptomyces_ghanaensis = 752,
  Streptomyces_griseoflavus = 753,
  Streptomyces_griseus = 754,
  Streptomyces_hygroscopicus = 755,
  Streptomyces_lividans = 756,
  Streptomyces_pristinaespiralis = 757,
  Streptomyces_roseosporus = 758,
  Streptomyces_scabiei = 759,
  Streptomyces_sviceus = 760,
  Streptomyces_violaceusniger = 761,
  Streptomyces_viridochromogenes = 762,
  Sulfolobus_acidocaldarius = 763,
  Sulfolobus_islandicus = 764,
  Sulfolobus_solfataricus = 765,
  Sulfolobus_tokodaii = 766,
  Sulfurihydrogenibium_azorense = 767,
  Sulfurihydrogenibium_yellowstonense = 768,
  Sulfurimonas_autotrophica = 769,
  Sulfurimonas_denitrificans = 770,
  Synechococcus_elongatus = 771,
  Thermaerobacter_marianensis = 772,
  Thermaerobacter_subterraneus = 773,
  Thermoanaerobacter_brockii = 774,
  Thermoanaerobacter_ethanolicus = 775,
  Thermoanaerobacter_italicus = 776,
  Thermoanaerobacterium_thermosaccharolyticum = 777,
  Thermoanaerobacterium_xylanolyticum = 778,
  Thermoanaerobacter_mathranii = 779,
  Thermoanaerobacter_pseudethanolicus = 780,
  Thermoanaerobacter_wiegelii = 781,
  Thermococcus_barophilus = 782,
  Thermococcus_gammatolerans = 783,
  Thermococcus_kodakaraensis = 784,
  Thermococcus_onnurineus = 785,
  Thermococcus_sibiricus = 786,
  Thermoplasma_acidophilum = 787,
  Thermoplasma_volcanium = 788,
  Thermosipho_africanus = 789,
  Thermosipho_melanesiensis = 790,
  Thermotoga_lettingae = 791,
  Thermotoga_maritima = 792,
  Thermotoga_naphthophila = 793,
  Thermotoga_neapolitana = 794,
  Thermotoga_petrophila = 795,
  Thermus_aquaticus = 796,
  Thermus_scotoductus = 797,
  Thermus_thermophilus = 798,
  Treponema_denticola = 799,
  Treponema_pallidum = 800,
  Treponema_phagedenis = 801,
  Treponema_vincentii = 802,
  Ureaplasma_parvum = 803,
  Ureaplasma_urealyticum = 804,
  Veillonella_atypica = 805,
  Veillonella_dispar = 806,
  Veillonella_parvula = 807,
  Vibrio_alginolyticus = 808,
  Vibrio_brasiliensis = 809,
  Vibrio_campbellii = 810,
  Vibrio_caribbenthicus = 811,
  Vibrio_cholerae = 812,
  Vibrio_coralliilyticus = 813,
  Vibrio_furnissii = 814,
  Vibrio_harveyi = 815,
  Vibrio_metschnikovii = 816,
  Vibrio_mimicus = 817,
  Vibrio_orientalis = 818,
  Vibrio_parahaemolyticus = 819,
  Vibrio_shilonii = 820,
  Vibrio_sinaloensis = 821,
  Vibrio_splendidus = 822,
  Vibrio_vulnificus = 823,
  Vulcanisaeta_distributa = 824,
  Vulcanisaeta_moutnovskia = 825,
  Wolbachia_endosymbiont = 826,
  Wolbachia_pipientis = 827,
  Xanthomonas_albilineans = 828,
  Xanthomonas_axonopodis = 829,
  Xanthomonas_campestris = 830,
  Xanthomonas_fuscans = 831,
  Xanthomonas_oryzae = 832,
  Xenorhabdus_bovienii = 833,
  Xenorhabdus_nematophila = 834,
  Yersinia_aldovae = 835,
  Yersinia_bercovieri = 836,
  Yersinia_enterocolitica = 837,
  Yersinia_frederiksenii = 838,
  Yersinia_intermedia = 839,
  Yersinia_kristensenii = 840,
  Yersinia_mollaretii = 841,
  Yersinia_pestis = 842,
  Yersinia_pseudotuberculosis = 843,
  Yersinia_rohdei = 844,
  Yersinia_ruckeri = 845,
  Sother= 846
} Species;

#define NUM_SPECIES 847

 #endif

#ifdef TB


typedef enum 
 {
   MTBC = 0,
   NTM = 1
  } PhyloGroup ;

#define NUM_COMPLEX 2

typedef enum 
 {
  abscessus = 0,
  africanum = 1,
  aromaticivorans = 2,
  avium = 3,
  bovis = 4,
  branderi = 5,
  caprae = 6,
  chelonae = 7,
  chlorophenolicum = 8,
  chubuense = 9,
  colombiense = 10,
  crocinum = 11,
  flavescens = 12,
  fluoranthenivorans = 13,
  fortuitum = 14,
  gilvum = 15,
  gordonae = 16,
  hodleri = 17,
  interjectum = 18,
  intracellulare = 19,
  kansasii = 20,
  lentiflavum = 21,
  leprae = 22,
  malmoense = 23,
  marinum = 24,
  mucogenicum = 25, 
  pallens = 26, 
  peregrinum = 27, 
  phage = 28, 
  pyrenivorans = 29, 
  rufum = 30,
  rutilum = 31,
  scrofulaceum = 32,
  senegalense = 33,
  smegmatis = 34,
  sphagni = 35,
  szulgai = 36,
  triplex = 37,
  tuberculosis = 38,
  tusciae = 39,
  ulcerans = 40,
  vaccae = 41,
  xenopi = 42
  } Species ;

#define NUM_SPECIES 43

  typedef enum 
 {
  beijing = 0,
  lineage1 = 1,
  lineage2 = 2, 
  lineage3 = 3, 
  lineage4 = 4, 
  lineage5 = 5
  } Lineage ;
 #define NUM_LINEAGES 6

void map_lineage_enum_to_str(Lineage sp, StrBuf* sbuf);
char* get_char_name_of_lineage_enum(Lineage lineage);


 #endif
typedef struct
{
  boolean present[NUM_SPECIES];
  int percentage_coverage[NUM_SPECIES];
  int median_coverage[NUM_SPECIES];
  int percentage_threshold[NUM_SPECIES];  
  int num_panels_present;
  int NUM_PANELS;
} CovgInfo;

typedef struct
{
  CovgInfo* phylo_group_covg_info;
  CovgInfo* species_covg_info;
  CovgInfo* lineage_covg_info;
  CovgInfo* other_covg_info;
} SpeciesInfo;

void map_phylo_group_enum_to_str(PhyloGroup sp, StrBuf* sbuf);
void map_species_enum_to_str(Species sp, StrBuf* sbuf);


void get_coverage_on_panels(int* percentage_coverage,int* median_coverage,
                            StrBuf** panel_file_paths,
                            int max_branch_len, dBGraph *db_graph,
                            int ignore_first, int ignore_last , int NUM_PANELS);

int get_ith_coverage_panel(CovgInfo* covg_info, int i);
int get_ith_present_panel(CovgInfo* covg_info, int i);


boolean is_percentage_coverage_above_threshold(int per_cov,int threshold);


CovgInfo* alloc_and_init_covg_info();
CovgInfo* get_coverage_info(dBGraph *db_graph,
                          StrBuf** file_paths,
                          int max_branch_len,
                          int NUM_PANELS,
                          int ignore_first,
                          int ignore_last,
                          void (*load_thresholds)()
                          );

int max(int int1,int int2);
int get_best_hit(CovgInfo* covg_info,boolean* mask);
boolean* create_mask(boolean default_value);
boolean panels_are_present(CovgInfo* covg_info ,  boolean* mask);

char* get_char_name_of_species_enum(Species species);

char* get_ith_phylo_group_name(CovgInfo* covg_info, int i);
char* get_ith_species_name(CovgInfo* covg_info, int i);
char* get_ith_lineage_name(CovgInfo* covg_info, int i);
void print_json_indiv_phylo(CovgInfo* covg_info,
                           char* (*get_ith_name)(CovgInfo*, int));
void print_json_phylogenetics(SpeciesInfo* species_info);
void print_json_phylo_group(SpeciesInfo* species_info);
void print_json_species(SpeciesInfo* species_info);
void print_json_lineage(SpeciesInfo* species_info);
